db-dev:
  driver:    mysql
  host:      localhost
  database:  uni_dev
  username:  root
  password:  123123
  collation: utf8_general_ci
  charset:   utf8

siteconf:
  port:    80
  docroot: /var/www/uni/public/
  dir:     /var/www/uni/
